sudo: required
language: generic
service:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t amsainfor/docker-react .

script:
  - docker run -e CI=true amsainfor/docker-react npm run test -- --coverage

#aws
#deploy:
#  provider: elasticbeanstalk
#  region: 'us-east-1'
#  app: 'docker'
#  env: 'docker-env'
#  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#  bucket_path: 'docker'
#  on:
#    branch: master

deploy:
  provider: azure_web_apps
#  skip_cleanup: true
  verbose: true
  username: AZURE_WA_USERNAME       # If AZURE_WA_USERNAME isn't set
  password: AZURE_WA_PASSWORD   # If AZURE_WA_PASSWORD isn't set
  site: AZURE_WA_SITE      # If AZURE_WA_SITE isn't set
  slot:       # (optional) If AZURE_WA_SLOT isn't set
  on:
   branch: master

   