#language: generic 
sudo: required
service:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t amsainfor/docker-react

script:
  - docker run -e CI=true amsainfor/docker-react npm run test -- --coverage